-- MySQL Script generated by MySQL Workbench
-- čet 13 dec 2018 17:27:58 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Schema Prodajalna
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Prodajalna` DEFAULT CHARACTER SET latin1 ;
USE `Prodajalna` ;

-- -----------------------------------------------------
-- Table `Prodajalna`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prodajalna`.`Item` (
  `Item_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Item_name` VARCHAR(50) NOT NULL,
  `Item_description` TEXT NULL DEFAULT NULL,
  `Item_URL` VARCHAR(255) NULL DEFAULT NULL,
  `Item_price` DECIMAL(10,0) NOT NULL,
  `Item_isApproved` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Item_ID`))
ENGINE = InnoDB

DEFAULT CHARACTER SET = latin1;



-- -----------------------------------------------------
-- Table `Prodajalna`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prodajalna`.`Customer` (
  `Customer_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Customer_firstName` VARCHAR(50) NOT NULL,
  `Customer_lastName` VARCHAR(255) NOT NULL,
  `Customer_email` VARCHAR(100) NOT NULL,
  `Customer_address` VARCHAR(255) NOT NULL,
  `Customer_city` VARCHAR(100) NOT NULL,
  `Customer_postNumber` INT(11) NOT NULL,
  `Customer_phoneNumber` VARCHAR(15) NOT NULL,
  `Customer_password` VARCHAR(15) NOT NULL,
  `Customer_isApproved` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Customer_ID`))
ENGINE = InnoDB

DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Prodajalna`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prodajalna`.`Staff` (
  `Staff_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Staff_firstName` VARCHAR(50) NOT NULL,
  `Staff_lastName` VARCHAR(255) NOT NULL,
  `Staff_email` VARCHAR(100) NOT NULL,
  `Staff_password` VARCHAR(15) NOT NULL,
  `Staff_isAdmin` TINYINT(1) NOT NULL,
  `Staff_isApproved` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Staff_ID`))
ENGINE = InnoDB

DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Prodajalna`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prodajalna`.`Order` (
  `Order_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Staff_ID` INT(11) NULL DEFAULT NULL,
  `Customer_ID` INT(11) NOT NULL,
  `Order_state` VARCHAR(50) NOT NULL,
  `Order_approvalDate` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`Order_ID`),
  INDEX `FK_order` (`Customer_ID` ASC),
  INDEX `FK_approve` (`Staff_ID` ASC),
  CONSTRAINT `FK_order`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `Prodajalna`.`Customer` (`Customer_ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_approve`
    FOREIGN KEY (`Staff_ID`)
    REFERENCES `Prodajalna`.`Staff` (`Staff_ID`))
ENGINE = InnoDB

DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Prodajalna`.`contains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prodajalna`.`contains` (
  `Item_ID` INT(11) NOT NULL DEFAULT '0',
  `Order_ID` INT(11) NOT NULL,
  `Price` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Item_ID`, `Order_ID`),
  INDEX `FK_contains2` (`Order_ID` ASC),
  CONSTRAINT `FK_contains`
    FOREIGN KEY (`Item_ID`)
    REFERENCES `Prodajalna`.`Item` (`Item_ID`),
  CONSTRAINT `FK_contains2`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `Prodajalna`.`Order` (`Order_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
